version: '3'

services:

  team01:
    build: .
    image: metasploit-team01
    ports:
    - "6201:6200"

  team02:
    build: .
    image: metasploit-team02
    ports:
    - "6202:6200"

  team03:
    build: .
    image: metasploit-team03
    ports:
    - "6203:6200"

  team04:
    build: .
    image: metasploit-team04
    ports:
    - "6204:6200"

  team05:
    build: .
    image: metasploit-team05
    ports:
    - "6205:6200"

  team06:
    build: .
    image: metasploit-team06
    ports:
    - "6206:6200"

networks:
    default:
    internal:
        internal: true
